name: 'github swift action'
description: 'Swift builder'
inputs: 
  action:
    description: 'script to run'
    required: true
  configuration:
    description: 'debug or release mode'
    required: false
  use_xcodebuild:
    description: 'using xcodebuild'
    required: false
  sdk:
    description: 'select sdk to build'
    required: false
  destination:
    description: 'destination for test'
    required: false
  enable_codecov:
    description: 'enable codecov'
    required: false
branding:
  color: 'orange' 
  icon: 'terminal'
runs:
  using: 'node12'
  main: 'index.js'
