name: Builder
on: [push, pull_request]
jobs:
  darwin:
    name: ${{ matrix.name }}
    runs-on: macOS-latest
    strategy:
      matrix:
        sdk: [macosx, iphonesimulator, appletvsimulator]
        include:
          - name: macOS
            sdk: macosx
            enable_codecov: true
          - name: iOS
            sdk: iphonesimulator
            destination: 'platform=iOS Simulator,name=iPhone 11'
          - name: tvOS
            sdk: appletvsimulator
            destination: 'platform=tvOS Simulator,name=Apple TV 4K'
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build
      uses: ./
      with:
        action: build
        use_xcodebuild: true
        sdk: ${{ matrix.sdk }}
        destination: ${{ matrix.destination }}
        enable_codecov: ${{ matrix.enable_codecov }}
    - name: Run tests
      uses: ./
      with:
        action: test
        use_xcodebuild: true
        sdk: ${{ matrix.sdk }}
        destination: ${{ matrix.destination }}
        enable_codecov: ${{ matrix.enable_codecov }}
    - uses: codecov/codecov-action@v1
      if: ${{ matrix.enable_codecov }}
  macos_swiftpm:
    name: macOS(SwiftPM)
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build
      uses: ./
      with:
        action: build
    - name: Run tests
      uses: ./
      with:
        action: test
  ubuntu:
    name: ${{ matrix.image }}
    container: 
      image: docker://swift:${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [xenial, bionic]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build
      uses: ./
      with:
        action: build
    - name: Run tests
      uses: ./
      with:
        action: test
