name: main
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      uses: ./
      with:
        action: build
    - name: Test
      uses: ./
      with:
        action: test
